
name: Build Test

on:
  push:
  pull_request:
    branches: master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "19"
      - name: Setup Project
        run: yarn
      - name: Build Project
        run: yarn build